### ISSUE TITLE
bad status line in bitcoind.getblockcount()

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstore#107]
Noticing a bitcoind error (I'm on branch:jude):

---------------------
[ERROR] [indexer:639] (68360) ''
Traceback (most recent call last):
  File "/Users/muneeb/.virtualenvs/test/lib/python2.7/site-packages/virtualchain/lib/indexer.py", line 635, in get_index_range
    current_block = int(bitcoind.getblockcount())
  File "/Users/muneeb/.virtualenvs/test/lib/python2.7/site-packages/bitcoinrpc/authproxy.py", line 114, in __call__
    response = self._get_response()
  File "/Users/muneeb/.virtualenvs/test/lib/python2.7/site-packages/bitcoinrpc/authproxy.py", line 134, in _get_response
    http_response = self.__conn.getresponse()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1073, in getresponse
    response.begin()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 379, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''
[ERROR] [blockstored:172] (68360) Reconnect to bitcoind

**Comment by jcnelson** [comment]
I think one of our bitcoind nodes is faulty.  Blockstore already automatically disconnects and reconnects itself whenever it notices this problem.

Looking more closely at when this error occurs, it seems to occur most often when the re-indexer subprocess wakes up and tries to figure out what the latest block count is.  I'll try forcing blockstored to always reconnect when it re-indexes and try running it for a few hours to see if the problem goes away.

**Comment by muneeb-ali** [comment]
Yeah, I also notice it when the re-indexer wakes up.

**Comment by muneeb-ali** [comment]
I'm not seeing this error anymore on the latest version.
