### ISSUE TITLE
import error in renew call

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstore#108]
2015-09-05 21:54:46-0400 [BlockstoredRPC,5,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/Users/muneeb/.virtualenvs/test/lib/python2.7/site-packages/twisted/internet/defer.py", line 296, in addCallbacks
	    self._runCallbacks()
	  File "/Users/muneeb/.virtualenvs/test/lib/python2.7/site-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/Users/muneeb/.virtualenvs/test/lib/python2.7/site-packages/txjsonrpc/netstring/jsonrpc.py", line 46, in <lambda>
	    parser, unmarshaller))
	  File "/Users/muneeb/.virtualenvs/test/lib/python2.7/site-packages/txjsonrpc/netstring/jsonrpc.py", line 55, in _cbDispatch
	    return defer.maybeDeferred(function, *args)
	--- <exception caught here> ---
	  File "/Users/muneeb/.virtualenvs/test/lib/python2.7/site-packages/twisted/internet/defer.py", line 140, in maybeDeferred
	    result = f(*args, **kw)
	  File "/Users/muneeb/Desktop/blockstore/blockstore/blockstored.py", line 441, in jsonrpc_renew
	    name_rec = db.get_name( name )
	exceptions.NameError: global name 'db' is not defined

**Comment by jcnelson** [comment]
Should be fixed in f6c7c14d0e8b23b610acdccf1fe92c8e8848f479

**Comment by muneeb-ali** [comment]
Awesome, thanks -- I'll pull the latest
