### ISSUE TITLE
db error after renew operation

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstore#110]
This test was for update op followed by renew op. Looks like a small error in updating last_renewed field in DB 
-----------
[ERROR] [virtualchain:93] (76527) list.remove(x): x not in list
Traceback (most recent call last):
  File "/Users/muneeb/.virtualenvs/test/lib/python2.7/site-packages/virtualchain/virtualchain.py", line 88, in sync_virtualchain
    state_engine.build( bitcoind_opts, last_block+1 )
  File "/Users/muneeb/.virtualenvs/test/lib/python2.7/site-packages/virtualchain/lib/indexer.py", line 565, in build
    consensus_hash = self.process_block( processed_block_id, txs )
  File "/Users/muneeb/.virtualenvs/test/lib/python2.7/site-packages/virtualchain/lib/indexer.py", line 512, in process_block
    self.commit_pending_ops( block_id, pending_ops )
  File "/Users/muneeb/.virtualenvs/test/lib/python2.7/site-packages/virtualchain/lib/indexer.py", line 495, in commit_pending_ops
    self.impl.db_commit( block_id, opcode, op_sanitized, db_state=self.state )
  File "/Users/muneeb/Desktop/blockstore/blockstore/lib/nameset/virtualchain_hooks.py", line 397, in db_commit
    db.commit_registration( op, block_id )
  File "/Users/muneeb/Desktop/blockstore/blockstore/lib/nameset/namedb.py", line 769, in commit_registration
    self.commit_renewal( nameop, current_block_number )
  File "/Users/muneeb/Desktop/blockstore/blockstore/lib/nameset/namedb.py", line 800, in commit_renewal
    self.block_name_renewals[ block_last_renewed ].remove( name )
ValueError: list.remove(x): x not in lis

**Comment by muneeb-ali** [comment]
confirmed fix
