### ISSUE TITLE
error during indexing

### ISSUE THREAD

**Issue by ericwooley** [blockstack/blockstore#166]
Got an error during indexing

```
[DEBUG] [transactions:483] (22124) Get 606 transactions from block 374045
[DEBUG] [transactions:618] (21292) blocks 374201-374263 (63):
[DEBUG] [transactions:619] (21292)   Time total:     50928.3813162
[DEBUG] [transactions:620] (21292)   Data total:     0
[DEBUG] [transactions:621] (21292)   Total goodput:  0.0
[DEBUG] [transactions:622] (21292)   block hash time:        6.17906880379
[DEBUG] [transactions:623] (21292)   block data time:        794.816362858
[DEBUG] [transactions:624] (21292)   block tx time:          952.23545289
[DEBUG] [transactions:625] (21292)   block nulldata tx time: 159.918995857
[DEBUG] [indexer:637] (21292) CONSENSUS(374200): 9e938749294b8019f9857cda93e7e73f
[DEBUG] [indexer:573] (21292) Process block 374201 (291 txs with nulldata)
[DEBUG] [virtualchain_hooks:504] (21292) Clear all expired names at 374201
[DEBUG] [virtualchain_hooks:507] (21292) Clear all expired preorders at 374201
[DEBUG] [virtualchain_hooks:510] (21292) Clear all expired namespace preorders at 374201
[DEBUG] [virtualchain_hooks:513] (21292) Clear all expired partial namespace imports at 374201
[DEBUG] [indexer:352] (21292) Snapshotting block 374201
[ERROR] [virtualchain:82] (21292) 'NoneType' object has no attribute 'encode'
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/virtualchain/virtualchain.py", line 77, in sync_virtualchain
    state_engine.build(bitcoind_opts, last_block+1)
  File "/Library/Python/2.7/site-packages/virtualchain/lib/indexer.py", line 641, in build
    consensus_hash = self.process_block( processed_block_id, txs )
  File "/Library/Python/2.7/site-packages/virtualchain/lib/indexer.py", line 579, in process_block
    consensus_hash = self.snapshot( block_id, pending_ops )
  File "/Library/Python/2.7/site-packages/virtualchain/lib/indexer.py", line 387, in snapshot
    merkle_tree = pybitcoin.MerkleTree( hashes )
  File "/Library/Python/2.7/site-packages/pybitcoin/merkle.py", line 51, in __init__
    hashes = hex_to_bin_reversed_hashes(hashes)
  File "/Library/Python/2.7/site-packages/pybitcoin/merkle.py", line 5, in hex_to_bin_reversed_hashes
    return [hex_to_bin_reversed(h) for h in hex_hashes]
  File "/Library/Python/2.7/site-packages/pybitcoin/hash.py", line 54, in hex_to_bin_reversed
    return unhexlify(s.encode('utf8'))[::-1]
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by yondonfu** [comment]
ever end up figuring out reason behind this? i'm encountering this error while indexing as well

**Comment by jcnelson** [comment]
This will be fixed in the next update.  We're currently reviewing the update right now (since it fixes a bunch of other things as well).

**Comment by jcnelson** [comment]
This should be fixed now; reopen if not.
