### ISSUE TITLE
btcd.onename.com connection issues

### ISSUE THREAD

**Issue by ericwooley** [blockstack/blockstore#170]
I can't seem to get btcd.onename.com to connect to the bitcoin cli
```bash
┌[ericwooley@blockstore]-(~)
└> bitcoin-cli --rpcuser=openname --rpcpassword=opennamesystem --rpcconnect=btcd.onename.com getpeerinfo
error: no response from server
```

or with blockstore-cli
```
blockstore-cli get_name_cost ericwooley-dev.id
Traceback (most recent call last):
  File "/usr/local/bin/blockstore-cli", line 4, in <module>
    __import__('pkg_resources').run_script('blockstore-client==0.0.2', 'blockstore-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/blockstore_client-0.0.2-py2.7.egg/EGG-INFO/scripts/blockstore-cli", line 893, in <module>
    run_cli()
  File "/usr/local/lib/python2.7/dist-packages/blockstore_client-0.0.2-py2.7.egg/EGG-INFO/scripts/blockstore-cli", line 858, in run_cli
    result = client.get_name_cost(str(args.name))
  File "/usr/local/lib/python2.7/dist-packages/blockstore_client-0.0.2-py2.7.egg/blockstore_client/client.py", line 454, in get_name_cost
    return proxy.get_name_cost(name)
  File "/usr/local/lib/python2.7/dist-packages/blockstore_client-0.0.2-py2.7.egg/blockstore_client/client.py", line 78, in default
    return self.request()
  File "/usr/local/lib/python2.7/dist-packages/blockstore_client-0.0.2-py2.7.egg/blockstore_client/client.py", line 93, in request
    self.ensure_connected()
  File "/usr/local/lib/python2.7/dist-packages/blockstore_client-0.0.2-py2.7.egg/blockstore_client/client.py", line 87, in ensure_connected
    self.sock.connect((self.server, self.port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused
```
This is from a digital ocean box with ubuntu 15 x64

**Comment by jcnelson** [comment]
Hi @ericwooley,

The `blockstore-cli` program connects to blockstored, not bitcoind.  If you have a blockstored instance running, be sure that the right host/port are set in `~/.blockstore-client/blockstore-client.ini`.

As for bitcoind, you need `-rpcssl` as well.

**Comment by ericwooley** [comment]
I removed everything and completely reinstalled, and it went away, @jcnelson Thanks for the advice, I didn't touch ~/.blockstore-client/blockstore-client.ini, so I don't know how that could have been screwed up. But it's gone now.
