### ISSUE TITLE
Workpool error

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstore#197]
I'm trying the latest branch:jude with the latest virtualchain branch:jude and getting the following error in the workpool:

```
[DEBUG] [workpool:317] (65311) 65341 input is full
[DEBUG] [workpool:317] (65311) 65341 input is full
[DEBUG] [workpool:317] (65311) 65341 input is full
[DEBUG] [workpool:317] (65311) 65341 input is full
[DEBUG] [workpool:317] (65311) 65341 input is full
[DEBUG] [workpool:317] (65311) 65341 input is full
[DEBUG] [workpool:317] (65311) 65341 input is full
[DEBUG] [workpool:317] (65311) 65341 input is full
[DEBUG] [workpool:317] (65311) 65341 input is full
[ERROR] [virtualchain:78] (65311) must be string, not exceptions.OSError
Traceback (most recent call last):
  File "/Users/muneeb/.virtualenvs/blockstore/lib/python2.7/site-packages/virtualchain/virtualchain.py", line 73, in sync_virtualchain
    indexer.StateEngine.build(bitcoind_opts, last_block+1, state_engine)
  File "/Users/muneeb/.virtualenvs/blockstore/lib/python2.7/site-packages/virtualchain/lib/indexer.py", line 775, in build
    block_ids_and_txs = transactions.get_nulldata_txs_in_blocks( state_engine.get_workpool(), bitcoind_opts, block_ids )
  File "/Users/muneeb/.virtualenvs/blockstore/lib/python2.7/site-packages/virtualchain/lib/blockchain/transactions.py", line 527, in get_nulldata_txs_in_blocks
    block_hash = future_get_result( block_hash_fut, 10000000000000000L )
  File "/Users/muneeb/.virtualenvs/blockstore/lib/python2.7/site-packages/virtualchain/lib/blockchain/transactions.py", line 447, in future_get_result
    return pickle.loads( result )
TypeError: must be string, not exceptions.OSError
```

**Comment by jcnelson** [comment]
Can you give virtualchain commit 424b30e a try?  It will at least print the stack trace of the OSError before bailing (instead of trying to parse it as a string).

**Comment by muneeb-ali** [comment]
Two errors:

```
DEBUG] [transactions:246] (66196) Get block hash for 386554
Traceback (most recent call last):
  File "/Users/muneeb/.virtualenvs/blockstore-testing/lib/python2.7/site-packages/virtualchain/lib/indexer.py", line 41, in <module>
    import pybitcoin
ImportError: No module named pybitcoin
Traceback (most recent call last):
  File "/Users/muneeb/.virtualenvs/blockstore-testing/lib/python2.7/site-packages/virtualchain/lib/indexer.py", line 41, in <module>
    import pybitcoin
ImportError: No module named pybitcoin
[DEBUG] [workpool:322] (66196) 66203 input is full
```

This one is strange because pybitcoin is installed in the virtualenv

The next one is 
```
[DEBUG] [workpool:322] (66196) 66203 input is full
[DEBUG] [workpool:322] (66196) 66203 input is full
[ERROR] [virtualchain:78] (66196) Child 66203 died unexpectedly
Traceback (most recent call last):
  File "/Users/muneeb/.virtualenvs/blockstore-testing/lib/python2.7/site-packages/virtualchain/virtualchain.py", line 73, in sync_virtualchain
    indexer.StateEngine.build(bitcoind_opts, last_block+1, state_engine)
  File "/Users/muneeb/.virtualenvs/blockstore-testing/lib/python2.7/site-packages/virtualchain/lib/indexer.py", line 775, in build
    block_ids_and_txs = transactions.get_nulldata_txs_in_blocks( state_engine.get_workpool(), bitcoind_opts, block_ids )
  File "/Users/muneeb/.virtualenvs/blockstore-testing/lib/python2.7/site-packages/virtualchain/lib/blockchain/transactions.py", line 527, in get_nulldata_txs_in_blocks
    block_hash = future_get_result( block_hash_fut, 10000000000000000L )
  File "/Users/muneeb/.virtualenvs/blockstore-testing/lib/python2.7/site-packages/virtualchain/lib/blockchain/transactions.py", line 446, in future_get_result
    result = fut.get( timeout )
  File "/Users/muneeb/.virtualenvs/blockstore-testing/lib/python2.7/site-packages/virtualchain/lib/workpool.py", line 83, in get
    raise self.result
OSError: Child 66203 died unexpectedly
[DEBUG] [indexer:759] (66196) Process blocks 386554 to 386555
```

**Comment by jcnelson** [comment]
Okay, it looks like the workers are trying to run `import pybitcoin` and crashing, which in turn (correctly) raises an OSError to the main process telling them that the workers died unexpectedly.

As a security precaution, the worker's environment variables are cleared before they are executed.  If `pybitcoin` is not installed to one of Python's default search paths (i.e. you're using the `PYTHONPATH` environment variable), this sort of thing can happen.  I'll update `virtualchain` so the index worker will inherit `PYTHONPATH` if it is defined in the parent process, and see if that clears this up.

**Comment by jcnelson** [comment]
Added PYTHONPATH propagation in blockstore:9557dd0 and virtualchain:c06e5a4.  Can you give these a try?

**Comment by muneeb-ali** [comment]
Getting the same error. I actually also tried installing pybitcoin outside of the virtualenv and got the same error. BTW my PYTHONPATH is empty (both inside the virtualenv and outside)

**Comment by muneeb-ali** [comment]
Wait. Trying something.

**Comment by muneeb-ali** [comment]
I updated virtualchain earlier and didn't update blockstore. Just did that. The pybicoin error disappears! 

Now I'm getting:

```
[DEBUG] [workpool:322] (66984) 66998 input is full
[DEBUG] [workpool:322] (66984) 66999 input is full
[DEBUG] [workpool:322] (66984) 67000 input is full
[DEBUG] [workpool:322] (66984) 66991 input is full
[DEBUG] [workpool:322] (66984) 66992 input is full
[DEBUG] [workpool:322] (66984) 66993 input is full
[DEBUG] [workpool:322] (66984) 66994 input is full
[DEBUG] [workpool:322] (66984) 66995 input is full
[DEBUG] [workpool:322] (66984) 66996 input is full
[DEBUG] [workpool:322] (66984) 66997 input is full
[DEBUG] [workpool:322] (66984) 66998 input is full
[DEBUG] [workpool:322] (66984) 66999 input is full
[DEBUG] [workpool:322] (66984) 67000 input is full
[DEBUG] [workpool:322] (66984) 66991 input is full
[ERROR] [virtualchain:78] (66984) Already indexing
Traceback (most recent call last):
  File "/Users/muneeb/.virtualenvs/blockstore-testing/lib/python2.7/site-packages/virtualchain/virtualchain.py", line 73, in sync_virtualchain
    indexer.StateEngine.build(bitcoind_opts, last_block+1, state_engine)
  File "/Users/muneeb/.virtualenvs/blockstore-testing/lib/python2.7/site-packages/virtualchain/lib/indexer.py", line 755, in build
    state_engine.start_workpool( bitcoind_opts )
  File "/Users/muneeb/.virtualenvs/blockstore-testing/lib/python2.7/site-packages/virtualchain/lib/indexer.py", line 697, in start_workpool
    raise Exception("Already indexing")
Exception: Already indexing
```

As the only log messages in a loop. My local DB is fully synced BTW.

**Comment by muneeb-ali** [comment]
I just verified on a Debian server that the current version works fine both inside and outside virtualenv. 

This is likely an OS X issue.

**Comment by muneeb-ali** [comment]
Fixed in develop branch of virtualchain in commit:

https://github.com/blockstack/virtualchain/commit/a1683753eada03ec076e2aa4477d0f7c092e5b96
